# Generated by Django 5.2 on 2025-05-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_options_blog_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.CharField(
                choices=[
                    ("free", "자유"),
                    ("music", "음악"),
                    ("game", "게임"),
                    ("study", "공부"),
                ],
                default="free",
                max_length=10,
                verbose_name="카테고리",
            ),
        ),
    ]
