# Generated by Django 5.2 on 2025-05-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ("-created_at", "-id"),
                "verbose_name": "댓글",
                "verbose_name_plural": "댓글 목록",
            },
        ),
    ]
