# Generated by Django 5.2.1 on 2025-05-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0002_userfollowing_user_following"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userfollowing",
            unique_together={("to_user", "from_user")},
        ),
    ]
